### ISSUE TITLE
Lack of data folder after building.

### ISSUE THREAD

**Issue by shoter** [milleniumbug/DidacticalEnigma#57]
If we download repository and try to run it as it is we will be faced with this error:

Exception:
System.IO.DirectoryNotFoundException: 'Could not find a part of the path 'C:\code\DidacticalEnigma\DidacticalEnigma\bin\Debug\Data\mecab\ipadic\char.bin'.'

Image:
![obraz](https://user-images.githubusercontent.com/3819892/47862447-6ff73c80-ddf5-11e8-8402-8758c6010702.png)

Proposed solution:
The data folder should be copied after project build.

---

I will try to do this with simple .bat scripts to copy whole data folder after successfull build.

**Comment by milleniumbug** [comment]
Ah, yes. The build system used to copy the files before - but that was due to NMeCab's implementation of how it copied stuff. This has been replaced.

It should be rather easy to make it work by including the submodule directory as part of the project and marking the files as "Copy if newer". I'll look into it later.

**Comment by milleniumbug** [comment]
Merged PR.
